### ISSUE TITLE
脚本报错了

### ISSUE THREAD

**Issue by joshuachenn** [Pr0214/trace_natives#1]
C:\Program Files\IDA 7.0\plugins\traceNatives.py: invalid syntax (C:/Program Files/IDA 7.0/plugins/traceNatives.py, line 64)
Traceback (most recent call last):
  File "C:\Program Files\IDA 7.0\python\ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files/IDA 7.0/plugins/traceNatives.py", line 64
    search_result = [f"-a '{so_name}!{offset}'" for offset in search_result]
                                                ^
SyntaxError: invalid syntax

**Comment by sionnx** [comment]
➕1

**Comment by xingkong123600** [comment]
+1

**Comment by Pr0214** [comment]
暂不支持7.0
